---
title: "Simple document"
output: html_document
---

I'm an R Markdown document! 

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("instacart")

view(instacart)

instacart %>% count(aisle, sort = TRUE)
```

There are about `r length(unique(instacart$aisle_id))`aisles in total. The aisle with the most amount of items ordered would be fresh vegetables.

```{r}

instacart |> count(aisle, sort = TRUE) |> filter(n > 10000) |>
  mutate(aisle = reorder(aisle, n)) |> ggplot(aes(x = n, y = aisle)) +
  geom_col() +  labs(x = "Total Number of Items", y = "Aisle")

```

```{r}

instacart |> filter(aisle == "packaged vegetables fruits" | aisle == "dog food care" |
                      aisle == "baking ingredients") |> 
                      count(aisle, product_name, sort = TRUE) |> group_by(aisle) |>
                      slice_max(order_by = n, n = 3) |>
                      arrange(aisle, n) |>
                      mutate(`Number of Times Ordered` = n) |>
                      select(-n)

```

```{r}

instacart |> filter(product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream") |> mutate(order_dow = case_when(
            order_dow == 0 ~ "Sunday",
            order_dow == 1 ~ "Monday",
            order_dow == 2 ~ "Tuesday",
            order_dow == 3 ~ "Wednesday",
            order_dow == 4 ~ "Thursday",
            order_dow == 5 ~ "Friday",
            order_dow == 6 ~ "Saturday",
          )) |> group_by(product_name, order_dow) |>
          summarize(mean_hour = mean(order_hour_of_day)) |>
          pivot_wider(
            names_from = order_dow,
            values_from = mean_hour
          )

```

# Section 2

I can take the mean of the sample, too!
